### PR TITLE
Update changelog for 1.2.1

### PR DESCRIPTION
**Pull request by wooorm**
Hey there, we’ve accumulated some fixes that I think should be released. A patch, I think.

@Flet, wdyt? Can we release this?

### CODE REVIEW

**Comment by Flet** [comment]
Yeah for sure!

**Comment by Flet** [comment]
@wooorm you want to publish or shall I?

**Comment by wooorm** [comment]
Feel free to publish!

> #### [Releases](https://github.com/Flet/github-slugger/blob/master/CONTRIBUTING.md)
> Declaring formal releases remains the prerogative of the project maintainer.

**Comment by wooorm** [comment]
[(although to be fair I also did a force push today, don’t tell anyone)](https://github.com/Flet/github-slugger/blob/master/CONTRIBUTING.md#rules)

**Comment by Flet** [comment]
Hah no worries :)

Published as 1.2.1 🎉

**Comment by wooorm** [comment]
Sweet, great!

**Comment by Flet** [comment]
Thanks for all your updates @wooorm feel free to publish to npm without me if necessary! This package is not on my radar lately.

**Comment by wooorm** [comment]
Alright, I’ll keep that in mind and try to help maintain this better 👍

**Pull request merged**
