### PR TITLE
add slug with occurrences

### LINKED ISSUE #19: id collision with number in text
```js
var GithubSlugger = require('github-slugger')
var slugger = new GithubSlugger()

slugger.slug('foo')
// returns 'foo'

slugger.slug('foo')
// returns 'foo-1'

slugger.slug('foo 1')
// returns 'foo-1'
```

This outputs two of the same slugs

### PR DESCRIPTION
**Pull request by UziTech**
add slug with occurrences to the occurrences array to prevent collisions with text ending in a number

Fixes #19

### CODE REVIEW

**Comment by UziTech** [comment]
right now I have it recursively check each slug with its occurrence to prevent collisions but I'm not sure if that is the best option. When a slug with an occurrence exists should it just add another occurrence or should it increment the occurrence.

```js
var GithubSlugger = require('github-slugger')
var slugger = new GithubSlugger()

slugger.slug('foo-1')
// returns 'foo-1'

slugger.slug('foo')
// returns 'foo'

slugger.slug('foo')
// returns 'foo-1-1'
// should it return 'foo-2'?
```

**Comment by wooorm** [comment]
@UziTech For your question, that depends on what GH is doing! This project should match that. For an example, I’ve created a little markdown file that shows that to people in a PR here: https://github.com/Flet/github-slugger/pull/17

**Comment by UziTech** [comment]
it looks like github sets the second foo to [foo-2](https://github.com/UziTech/test/blob/master/README.md#foo-2)

**Comment by UziTech** [comment]
I changed it so it matches github

```js
var GithubSlugger = require('github-slugger')
var slugger = new GithubSlugger()

slugger.slug('foo-1')
// returns 'foo-1'

slugger.slug('foo')
// returns 'foo'

slugger.slug('foo')
// returns 'foo-2'
```

**Pull request merged**
